---
title: "Preprocesado de datos"
author: "ASR"
date: "21/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Plantilla para el preprocesado de datos

# Importar el dataset
```{r}
dataset = read.csv('Data.csv')
```

# Tratamiento de los valores NA
```{r}
dataset$Age = ifelse(is.na(dataset$Age), ave(dataset$Age, FUN = function(x) mean(x,na.rm=TRUE)),dataset$Age)

dataset$Salary = ifelse(is.na(dataset$Salary), ave(dataset$Salary, FUN = function(x) mean(x,na.rm=TRUE)),dataset$Salary)
```

# Codificar variables categóricas
```{r}
dataset$Country = factor(dataset$Country,levels=c("France","Spain","Germany"),labels=c(1,2,3))

dataset$Purchased = factor(dataset$Purchased,levels=c("No","Yes"),labels=c(0,1))
```

# Dividir en conjunto de test y entrenamiento
```{r}
library(caTools)
split = sample.split(dataset$Purchased, SplitRatio=0.8)
split
```

```{r}
training_set = subset(dataset,split == TRUE)
testing_set = subset(dataset,split == FALSE)
```

# Escalado de valores
```{r}
training_set[,2:3] = scale(training_set[,2:3])
testing_set[,2:3] = scale(testing_set[,2:3])
```

